<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows10.0.26100.0</TargetFramework>
    <IsTestProject>true</IsTestProject>
    <IsPackable>false</IsPackable>
    <IsPublishable>false</IsPublishable>
    <Platforms>x64</Platforms>
    <BaseOutputPath>$(RepoRoot)build\test-bin\</BaseOutputPath>
    <OutputPath>$(BaseOutputPath)$(Platform)\$(Configuration)\</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="coverlet.collector" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\managed\Wildpinkler.App\Wildpinkler.App.csproj" />
  </ItemGroup>

</Project>
